name: pytorch
channels:
  - conda-forge
  - pytorch
dependencies:
  - python==3.6.1
  - opencv
  - matplotlib=2.0.2
  - pytorch=1.2.0
  - torchvision=0.4.0
#   - cudatoolkit=8.0
  - absl-py=0.7.1
  - pip=9.0.1
  - pip:
    - tensorboardx==1.6
    - torchsummary
